### PR TITLE
Updated for Sympa 6.2.x

### PR DESCRIPTION
**Pull request by mundschenk-at**
I've updated the modified alias_manager.pl for the changes in Sympa 6.2.x (the old version would not run anymore because some Perl modules are not included anymore).

### CODE REVIEW

**Comment by mundschenk-at** [comment]
@tribut Not interested?

**Comment by tribut** [comment]
Sorry for my terrible response-time and thanks a lot for doing this. Will merge this weekend.

**Comment by tribut** [comment]
Thanks again for taking the time to open a pull request.

I'm trying to keep this repository in sync with Debian as much as possible (due to the corresponding guide being written for Debian) and it seems this change will break for existing users. You are using local install path (`/usr/local` - even for perl) and there are also some changes in the merge commit that are not purely merges which makes it hard for me to review.

My proposal would be to keep this PR open so people looking for a version compatible with 6.2 can find it and once 6.2 lands in sid, I will integrate your changes. Is this OK with you?

**Comment by mundschenk-at** [comment]
I patched things on FreeBSD where `/usr/local` is used for all ports by default. I would have no problem with changing the prefix. As for the other changes, what do you mean? Basically I manually applied your change to the vanilla 6.2 file I had on my system (I've not done any Perl coding in a long time, so maybe it was more rote than it should have been).

Anyway, it's your repository :-)

**Comment by mundschenk-at** [comment]
Hi! I just saw that Sympa 6.2.16 has landed in testing (as well as sid),should we start to work on this again?

**Comment by dereckson** [comment]
@mundschenk-at Could you create a branch `upgrade-to-sympa62` and apply as one commit either https://github.com/mundschenk-at/sympa-postfix-virtual/commit/42855c63cb98c61975d2f11892c3296c529e6976 either a new one for 6.2.16?

That would be the ideal, as a pull request is more easy to review if it only focus on one change.

**Comment by tribut** [comment]
Sorry for keeping silent on this. Thanks for reminding me about 6.2 in Debian. Definitly got this on my todo-list, just a lot of things going on currently.

**Comment by mundschenk-at** [comment]
Sure, I'll try to make a clean branch tomorrow.

**Comment by mundschenk-at** [comment]
Sorry, took a bit longer than expected. I've created #2 with a clean patch.

**Pull request closed without merging**
